dia = input('Que dia você nasceu? ')
mes = input('E que mês você nasceu? ')
ano = input('Agora só falta você me dizer o ano :) ')
print('A sua data de nascimento no formato brasileiro é', dia,'/',mes,'/',ano)
print('E no formato americano é', ano,'/',mes,'/',dia)
