# Faça um programa que receba um número inteiro qualquer e mostre sua tabuada

n = int(input('Digite um número no qual você queira saber a tabuada: '))
#print('='*13)
#print(n,'x 1  = ',n*1)
#print(n,'x 2  = ',n*2)
#print(n,'x 3  = ',n*3)
#print(n,'x 4  = ',n*4)
#print(n,'x 5  = ',n*5)
#print(n,'x 6  = ',n*6)
#print(n,'x 7  = ',n*7)
#print(n,'x 8  = ',n*8)
#print(n,'x 9  = ',n*9)
#print(n,'x 10 = ',n*10)
#(print('='*13))

# Resolução do Guanabara
print('='*12)
print('{} x {:2} = {}'.format(n, 1, n*1))
print('{} x {:2} = {}'.format(n, 2, n*2))
print('{} x {:2} = {}'.format(n, 3, n*3))
print('{} x {:2} = {}'.format(n, 4, n*4))
print('{} x {:2} = {}'.format(n, 5, n*5))
print('{} x {:2} = {}'.format(n, 6, n*6))
print('{} x {:2} = {}'.format(n, 7, n*7))
print('{} x {:2} = {}'.format(n, 8, n*8))
print('{} x {:2} = {}'.format(n, 9, n*9))
print('{} x {:2} = {}'.format(n, 10, n*10))
print('='*12)